### ISSUE TITLE
Upgrade question

### ISSUE THREAD

**Issue by dpierangeli** [jasonmayes/mdl-component-design-pattern#2]
Excuse me if i open an issue to ask a question, feel free to close it and point me to the correct channel.

I have a doubt about complex object, for example a table with body with rows.
If i add a row at run-time i need to re-call upgrade also for the table or only for the new row?

**Comment by jasonmayes** [comment]
You can specify the class of object you just added so it will only find new ones of that type that have not previously been upgraded to avoid duplication and efficiency. For further details it is best to post Q&A to the MDL repo as they may have changed code since I proposed this one. You can do that here: https://github.com/google/material-design-lite
